Pedidoapp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from .import views
from django.contrib.auth.views import login_required


from Pedidoapp.views import home, Cant_ingresar, ListAll, ListEspeci, Cant_update, PedidoExtra
from Pedidoapp.views import ExtraView, Cant_upex, Update_stockex, ReportePedidosPDF, ReporteTotalPDF, ReporteTotalFarmacia, ReporteTotalEcono 
from Pedidoapp.views import Reset, Acces_open, Acces_close, VistaAsigna, Asigna, DeletePedido, IngresarExtra, VerTodo, Entregar, Ped_entregados, ListAllEnt, Esp_total, ReportePedidoExtra

admin.autodiscover()

urlpatterns = [

url(r'^home/', login_required(home), name="home"),
url(r'^pedidos-entregados/$', login_required(Ped_entregados), name="ped_entre"),
url(r'^especialidades/$', login_required(Esp_total), name="esp_total"),


url(r'^lista_super/(?P<id_especialidad>\d+)/$', login_required(ListAll), name='lita_todo'),
url(r'^lista_super_entregados/(?P<id_especialidad>\d+)/$', login_required(ListAllEnt), name='lita_todo_entre'),

url(r'^lista_active/(?P<id_especialidad>\d+)/$', login_required(ListEspeci), name='lita_active'),

url(r'^ingresar/(?P<id_pedido>\d+)/(?P<id_especialidad>\d+)/$', Cant_ingresar, name="cant_ingresar"),
url(r'^modificar/(?P<id_pedido>\d+)/(?P<id_especialidad>\d+)/$', Cant_update, name="cant_update"),
url(r'^entregar/(?P<id_especialidad>\d+)/$', Entregar, name="entregar"),

url(r'^pedido-extra/(?P<id_especialidad>\d+)/$', PedidoExtra , name='pedido_extra'),
url(r'^pedidos-extra/$', ExtraView , name='ped_ex'),
url(r'^modificar/(?P<id_pedido_ex>\d+)/$', Cant_upex, name="cant_extra"),
url(r'^ingresa-extra/(?P<id_especialidad>\d+)/(?P<cod_experto>[^/]+)/$', IngresarExtra, name="ingresa_extra"),
url(r'^entregar/(?P<id_pedido_ex>\d+)/(?P<cod_experto>[^/]+)/$', Update_stockex, name="entregado_ex"), 

url(r'^reset-estadis/$', login_required(Reset), name="reset"),
url(r'^acces-open/$', login_required(Acces_open), name="open"),
url(r'^acces-close/$', login_required(Acces_close), name="close"),

url(r'^reporte_pedidos_pdf/(?P<id_especialidad>\d+)/$', login_required(ReportePedidosPDF.as_view()), name="reporte_pedidos_pdf"),
url(r'^reporte_insumo_pdf/$', login_required(ReporteTotalPDF.as_view()), name="reporte_insumo_pdf"),
url(r'^reporte_farmacia_pdf/$', login_required(ReporteTotalFarmacia.as_view()), name="reporte_farma_pdf"),
url(r'^reporte_economato_pdf/$', login_required(ReporteTotalEcono.as_view()), name="reporte_econo_pdf"),
url(r'^reporte_extras_pdf/$', login_required(ReportePedidoExtra.as_view()), name="reporte_pedido_extra_pdf"),

url(r'^asignar-nuevo/(?P<id_especialidad>\d+)/$', login_required(VistaAsigna), name='vista_asigna'),
url(r'^vista-art-extra/(?P<id_especialidad>\d+)/$', login_required(VistaAsigna), name="vista_extra"),
url(r'^btn-asigna/(?P<id_especialidad>\d+)/(?P<cod_experto>[^/]+)/$', Asigna, name="asignar"),
url(r'^delete-pedido/(?P<id_pedido>\d+)/(?P<id_especialidad>\d+)/(?P<cod_experto>[^/]+)/$', DeletePedido, name="confirm_delete_pedido"),
url(r'^ver_todo/(?P<id_especialidad>\d+)/$', login_required(VerTodo), name='ver_todo'),



]   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)      

bodega/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from Pedidoapp import urls
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf import settings


admin.autodiscover()


urlpatterns = [
    # Examples:
    url(r'^solicitar/', include(urls, namespace="usuario")),
  #  url(r'^home_user/$', login_required(Pedidoapp.views.homeuser), name="homeuser"),
    #url(r'^add/$', login_required(add), name=""), 

    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli /',include('grappelli.urls')),
    url(r'^grappelli /',include('grappelli.urls')),
    url(r'^accounts/login/', login, {'template_name':'login.html'}, name="login"),
    url(r'^$', login, {'template_name':'login.html'}, name="login"),
    url(r'^logout/', logout_then_login, name="logout"),


    

]

Pedidoapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Pedido, Especialidad, Articulo, Pedido_Extra


class PedidoEditForm(forms.ModelForm):
    cantidad       = forms.IntegerField(widget=forms.TextInput(attrs={'multiple': True}))

    class Meta:
        model = Pedido


        fields = [

        'cantidad',

        ]  

class PedAdminEditForm(forms.ModelForm):
    cantidad_update       = forms.IntegerField(label='Cantidad:', widget=forms.TextInput(attrs={'type':'number'}))

    class Meta:
        model = Pedido


        fields = [

        'cantidad_update',

        ] 

class EstadisticaForm(forms.ModelForm):
    estadistica    = forms.IntegerField(label='Estadistica Mensual:', widget=forms.TextInput(attrs={'placeholder':'Ingrese numero pacientes'}))  
    
    class Meta:
        model = Especialidad

        fields = [

        'estadistica',

        ]

class ExtraForm(forms.ModelForm):
    cantidad_ex       = forms.IntegerField(label='Cantidad:', widget=forms.TextInput(attrs={'size':'10'}))
    

    class Meta:
        model = Pedido_Extra


        fields = [
        'cantidad_ex',
        
        ]

Pedidoapp/views.py
#!/usr/bin/env python
#-*- coding: utf-8 -*- 

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from Pedidoapp.models import Pedido, Especialidad, Encargado, Articulo, Bodega, Pedido_Extra
from django.shortcuts import render_to_response
from django.template.loader import get_template
from django.template import Context
from datetime import datetime
from Pedidoapp.forms import PedidoEditForm,PedAdminEditForm, EstadisticaForm, ExtraForm
from django.template.context import RequestContext
from django.template import RequestContext
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.shortcuts import get_list_or_404, get_object_or_404
from django.db import models
from django.db.models import Count
from django.core.urlresolvers import reverse
import datetime
from django.utils import timezone
from django.views.generic import CreateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import psycopg2
import sys
import json

from django.contrib.auth.views import login


#modificar filtracion de las especialidades no es necesario mostrar numero de articulos, aun asi, si el numero de entregados
#o el numero de pendientes filtrar por estos camopos: esp = Especialida
def home(request):
    user = request.user
    if user.is_superuser:
      especialidad = Especialidad.objects.filter(estado="pendiente")
      acceso = Especialidad.objects.filter(acceso=0)
      count = Especialidad.objects.filter(estado="pendiente").count()
      count2 = Especialidad.objects.filter(estado="entregado").count()
      count3 = Especialidad.objects.all().count()
      count4 = Especialidad.objects.filter(estado="completado").count() 

      page = request.GET.get('page', 1)

      paginator = Paginator(especialidad, 5)
      try:
            especialidad = paginator.page(page)
      except PageNotAnInteger:
            especialidad = paginator.page(1)
      except EmptyPage:
            especialidad = paginator.page(paginator.num_pages)

      return render(request, "indexadmin.html", {'especialidad':especialidad, 'count':count, 'count2':count2, 'count3':count3, 'acceso':acceso})

    elif user.is_active: 
      especialidad  = Especialidad.objects.filter(encargado__usuario=user.id)
      template2 = "index3.html"
      return render(request, template2, { 'especialidad':especialidad })



def Ped_entregados(request):
    user = request.user
    if user.is_superuser:
      especialidad = Especialidad.objects.filter(estado="entregado").order_by('nombre')
      acceso = Especialidad.objects.filter(acceso=0)
      count = Especialidad.objects.filter(estado="pendiente").count()
      count2 = Especialidad.objects.filter(estado="entregado").count()
      count3 = Especialidad.objects.all().count()
      template = "indexadmin.html"
      page = request.GET.get('page', 1)

      paginator = Paginator(especialidad, 5)
      try:
            especialidad = paginator.page(page)
      except PageNotAnInteger:
            especialidad = paginator.page(1)
      except EmptyPage:
            especialidad = paginator.page(paginator.num_pages)

      return render(request, template, {'especialidad':especialidad, 'count':count, 'count2':count2, 'count3':count3, 'acceso':acceso})


def Esp_total(request):
      user = request.user
      if user.is_superuser:
         especialidad = Especialidad.objects.all().order_by('nombre')
         acceso = Especialidad.objects.filter(acceso=0)
         count = Especialidad.objects.filter(estado="pendiente").count()
         count2 = Especialidad.objects.filter(estado="entregado").count()
         count3 = Especialidad.objects.all().count()
         template = "indexadmin.html"
         page = request.GET.get('page', 1)

         paginator = Paginator(especialidad, 5)
         try:
                  especialidad = paginator.page(page)
         except PageNotAnInteger:
                  especialidad = paginator.page(1)
         except EmptyPage:
                  especialidad = paginator.page(paginator.num_pages)

         return render(request, template, {'especialidad':especialidad, 'count':count, 'count2':count2, 'count3':count3, 'acceso':acceso})


#LISTA ADMIN PENDIENTES
@cache_page(1000)
@login_required
def ListAll(request, id_especialidad):
  especialidad = Especialidad.objects.get(id=id_especialidad)
  if request.method == 'GET':
        pedido = Pedido.objects.filter(especialidad=especialidad).filter(estado='pendiente').order_by('-estado').order_by('articulo')
        template  = 'admindata.html'
        return render(request, template, {'pedido':pedido, 'especialidad':especialidad})

#LISTA ADMIN ENTREGADOS
@cache_page(1000)
@login_required
def ListAllEnt(request, id_especialidad):
  especialidad = Especialidad.objects.get(id=id_especialidad)
  if request.method == 'GET':
        pedido = Pedido.objects.filter(especialidad=especialidad).filter(estado='entregado').order_by('articulo')
        template  = 'admindata2.html'
        return render(request, template, {'pedido':pedido, 'especialidad':especialidad})



#LISTA ACTIVO
@cache_page(1000)
@login_required
def ListEspeci(request, id_especialidad):
      especialidad = Especialidad.objects.get(id=id_especialidad)
      pedido2 = Pedido.objects.filter(especialidad=especialidad).filter(estado='pendiente').order_by('-articulo')
      pedido3 = Pedido.objects.filter(especialidad=especialidad).filter(estado='entregado').order_by('-articulo')
      pedido = Pedido.objects.filter(especialidad=especialidad)
      if request.method == 'GET':
            form = EstadisticaForm(instance=especialidad)
      else:
            form = EstadisticaForm(request.POST, instance=especialidad)
            if form.is_valid():
                  form.save()
            return HttpResponseRedirect('/solicitar/lista_active/%s/' % id_especialidad)
      return render(request, 'index2.html', { 'form':form, 'pedido':pedido, 'pedido2':pedido2, 'pedido3':pedido3, 'especialidad':especialidad})
 


#BTN INGRESAR ACTIVO
@login_required
@cache_page(1000)
def Cant_ingresar(request, id_pedido, id_especialidad):
    especialidad = Especialidad.objects.get(id=id_especialidad)
    pedido = Pedido.objects.get(id=id_pedido)
    
    if request.method == 'GET':
      form = PedidoEditForm(instance=pedido)
    else:
      form = PedidoEditForm(request.POST, instance=pedido)
      if form.is_valid():
          form.save()
          pedido2 = Pedido.objects.filter(id=id_pedido).update(estado="pendiente", fecha_pedido=timezone.now())
          Especialidad.objects.filter(id=id_especialidad).update(estado="pendiente")
      return HttpResponseRedirect('/solicitar/lista_active/%s/' % id_especialidad)
    return render(request, 'form.html', {'form':form, 'pedido':pedido, 'especialidad':especialidad, 'pedido':pedido}) 


#BTN MODIFICAR ADMIN
@login_required
@cache_page(1000)
def Cant_update(request, id_pedido, id_especialidad):
    especialidad = Especialidad.objects.get(id=id_especialidad)
    pedido = Pedido.objects.get(id=id_pedido)
    if request.method == 'GET':
      form = PedAdminEditForm(instance=pedido)
    else:
      form = PedAdminEditForm(request.POST, instance=pedido)
      if form.is_valid():
          form.save()
          pedido.estado_update = 'modificado'
          pedido.save()
      return HttpResponseRedirect('/solicitar/lista_super/%s/' % id_especialidad)
    return render(request, 'form3.html', {'form':form, 'pedido':pedido, 'especialidad':especialidad})



from django.views.generic import ListView, DetailView
   

class PedidoDetailView(DetailView):
    model = Pedido
    def get_template_names(self):
        return render('index.html')


#BTN ENTREGADO
@login_required
def Entregar(request, id_especialidad):
    especialidad = Especialidad.objects.get(id=id_especialidad)
    pedido3 = Pedido.objects.filter(especialidad=especialidad).filter(estado='pendiente').update(fecha_entrega=timezone.now())
    for ped in Pedido.objects.filter(especialidad=especialidad).filter(estado='pendiente'):
      ped.estado = "entregado"
      ped.save()
      if ped.estado_update == "modificado":
            ped.articulo.stock -= ped.cantidad_update
      else: 
            ped.articulo.stock -= ped.cantidad
            ped.save()
    especialidad.estado = 'entregado'
    especialidad.save()
    return HttpResponseRedirect('/solicitar/reporte_pedidos_pdf/%s/' % id_especialidad)



#Ingresar cantidad de articulo extra
@login_required
def PedidoExtra(request, id_especialidad):
    especialidad = Especialidad.objects.get(id=id_especialidad)
    if request.method == 'GET':
      form = ExtraForm()
    else:
      form = ExtraForm(request.POST)
      if form.is_valid():
        esp = form.save(commit=False)
        esp.especialidad_ex = especialidad
        esp.save()
        form.save()
      return HttpResponseRedirect('/solicitar/home/')
    return render(request, 'form2.html', {'form':form, 'especialidad':especialidad})

#vista para admin y activo de extras
@login_required
def ExtraView(request):
      user = request.user
      if user.is_superuser:
        extra = Pedido_Extra.objects.filter(estado_ex='pendiente')
        return render(request, 'extra.html', {'extra':extra, 'user':user})
      else:
        extra = Pedido_Extra.objects.filter(especialidad_ex__encargado__usuario=user.id)
        return render(request, 'extra.html', {'extra':extra, 'user':user})

#admin modifica cantidad extra
@login_required
def Cant_upex(request, id_pedido_ex):
    extra = Pedido_Extra.objects.get(id=id_pedido_ex)
    if request.method == 'GET':
      form = ExtraForm(instance=extra)
    else:
      form = ExtraForm(request.POST, instance=extra)
      if form.is_valid():
          form.save()
          extra.save()
      return HttpResponseRedirect('/solicitar/pedidos-extra/')

Pedidoapp/templates/addmod.html
{% extends 'base/base.html' %}

{% block content %}
<!-- comentario de lo que sea -->
{% load static from staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <link rel="stylesheet" href="{% static "normalize.css" %}" />
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="{% static "estilos.css" %}" />
    <link rel="stylesheet" href="{% static "responsive.css" %}" />
    <link rel="stylesheet" href="{% static "dataTables.bootstrap.min.css" %}"/>
    <link rel="stylesheet" href="{% static "dataTables.checkboxes.css" %}"/>
</head>

<br>
<h4>Especialidad:&nbsp;&nbsp;<b>{{especialidad.nombre}}</b></h4>
<a href="{% url "usuario:vista_asigna" id_especialidad=especialidad.id %}" method='GET' type="submit" class
="btn btn-primary pull-right" value="editar"/>Nuevo</a></td>
<section id="contenido">
<form id="myform" method="post">
<table id="example" class="table table-border table-striped table-hover" >
<br>
<br>
            <thead>
                <tr> 
                    <td>Cod experto</td>
                    <td>Nombre</td>
                    <td>stock</td>
                    <td></td>
                </tr>
            </thead>
            <tfoot>
                <tr>

                    <td>Cod experto</td>
                    <td>Nombre</td>
                    <td>stock</td>
                    <td></td>
                </tr>
            </tfoot>
            <tbody>
        {% if pedido  %}
        {% for ped in pedido  %}
                <tr>
                    <td>{{ ped.articulo.cod_experto }}</td>
                    <td>{{ ped.articulo.nombre }}</td>
                    <td>{{ ped.articulo.stock }}</td>
                    
                    <td><a class="tag_item" href="{% url "usuario:confirm_delete_pedido" id_pedido=ped.id id_especialidad=especialidad.id cod_experto=ped.articulo.cod_experto %}" ><img src="/static/img/exis.png" width="16" height="16px"  /></a></td>
                </tr>
        {% endfor %}
        {% endif %}
           </tbody>
           </table>
           <a class="tag_item" href="{% url "usuario:reporte_pedidos_pdf" id_especialidad=especialidad.id %}" ><img src="/static/img/pdf.png" width="100" height="100px"  /></a>

            
</form>
</div>
</section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "js/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "js/dataTables.checkboxes.min.js" %}"></script>
    <script src="{% static "js/jquery.form.min.js" %}"></script>
    

    <script>
$(document).ready(function (){
   var table = $('#example').DataTable({
  
      'columnDefs': [
         {
            'targets': 0,
         }
      ],
   });

   table.column(0).every( function () {

    var column = this;
    var select = $('')
      .appendTo($(column.footer()).empty())
      .on('change', function() {
        var val = $.fn.dataTable.util.escapeRegex(
          $(this).val()
        );

        column
          .search(val ? '^' + val + '$' : '', true, false)
          .draw();
      });

    column.data().unique().sort().each(function(d, j) {
      select.append('<option value="' + d + '">' + d + '</option>')
    });

});

});

  </script>


{% endblock%}

Pedidoapp/templates/confirmar.html
{% extends 'base/base.html' %}
{% block content %}

<form method="post">
{% csrf_token %}
    <h3>¿Desea Aprobar esta solicitud: {{ ped.especialidad.nombre }}?</h3>  
    <button class="btn btn-success" type="submit">Aceptar</button>
    <a class= "btn btn-default" href="{% url 'usuario:home' %}">Cancelar</a>
    
</form>
{% endblock %}

Pedidoapp/templates/indexadmin.html
{% extends 'base/base.html' %}

{% block content %}
<!-- comentario de lo que sea -->
{% load static from staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <link rel="stylesheet" href="{% static "normalize.css" %}" />
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="{% static "estilos.css" %}" />
    <link rel="stylesheet" href="{% static "responsive.css" %}" />

</head>
<body>
    <section id="contenido">
    {% if request.user.is_superuser %}
    <article class="item">
            <figure class="imagen_item">
            {% if count == 0  %}
               {% if acceso  %}
            <a class="tag_item" href="{% url 'usuario:open' %}"><img src="/static/img/open.png" width="100" height="100px"  /></a>
            {% endif %}
                {% else %}
                   {% if count2 == 0  %}
            <a class="tag_item" href="{% url 'usuario:close' %}"><img src="/static/img/close.png" width="100" height="100px"  /></a>
                   {% endif %}
                {% endif %}
    {% endif %}
            </figure>
            <p class="datos_item">
            <a class="tag_item" href=""><b>ADMINISTRADOR</b></a>
            <br>
            <p class="autor_item">
            PDF BODEGAS: CANTIDAD TOTAL DE ESPECIALIDADES
            <br>
            <a class="titulo_item" href="{% url "usuario:reporte_insumo_pdf"  %}">INSUMO</a>
            <a class="titulo_item" href="{% url "usuario:reporte_farma_pdf"  %}">FARMACIA</a>
            <a class="titulo_item" href="{% url "usuario:reporte_econo_pdf"  %}">ECONOMATO</a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url "usuario:reset" %}" method='GET' type="submit" class="btn btn-danger pull-right" value="reset" onclick="document.location.reload();"/>Resetear</a>
            <br>
            <h5><b><a href="{% url "usuario:esp_total"  %}">Especialidades: {{ count3 }}</a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url "usuario:home"  %}">Pedidos Pendientes: {{ count }}</a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="{% url "usuario:ped_entre"  %}">Pedidos Entregados: {{ count2 }}</a></b></h5>

        </article>

    <section id="contenido">
        {% if especialidad %}
        
        {% for esp in especialidad %}
        
    <article class="item">
            <b>
            <figure class="imagen_item">
            {% if esp.estado == "pendiente" %}
            <a href="{% url "usuario:lita_todo" id_especialidad=esp.id %}"><img src="/static/img/user.png" width="1000" height="135px"  /></a>
            {% else %}
            {% if esp.estado == "entregado" %}
            <a href="{% url "usuario:lita_todo_entre" id_especialidad=esp.id %}"><img src="/static/img/user.png" width="1000" height="135px"  /></a>
            {% else %}
            {% if esp.estado == "completado" %}
            <a href="{% url "usuario:lita_todo" id_especialidad=esp.id %}"><img src="/static/img/user.png" width="1000" height="135px"  /></a>
            {% endif %}
            {% endif %}
            {% endif %}
            </figure>
            <p class="datos_item">
            {% if esp.estado == "pendiente" %}
            <a class="tag_item" href="{% url "usuario:lita_todo" id_especialidad=esp.id %}">{{esp.nombre}}</a>
            {% else %}
            {% if esp.estado == "entregado" %}
            <a class="tag_item" href="{% url "usuario:lita_todo_entre" id_especialidad=esp.id %}">{{esp.nombre}}</a>
            {% else %}
            {% if esp.estado == "completado" %}
            <a class="tag_item" href="{% url "usuario:lita_todo" id_especialidad=esp.id %}">{{esp.nombre}}</a>
            {% endif %}
            {% endif %}
            {% endif %}


            </p>
            <a class="titulo_item" href=""><h5>{{esp.encargado.nombre}}</a></h5></p>
           </p>
            {% if esp.acceso == 0 %}
            <p class="autor_item">
            {% endif %}
            {% if esp.estado == "entregado" %}
            <font color="blue"><h4><b>Pedido Entregado</b></h4></font>
            {% endif %}
            {% if esp.estado == "completado" %}
            <font color="red"><h4><b>Pedido sin solicitar.</b></h4></font>
            {% endif %}
            {% if esp.estado == "pendiente" %}
            <font color="green"><h4><b>Pedido Pendiente!</b></h4></font>
            {% endif %}
            <a href="{% url "usuario:ver_todo" id_especialidad=esp.id %}" method='GET' type="submit" class="btn btn-primary pull-right"/>Ver Todo</a>
            </p>   
            <p class="autor_item">
            
            </p>                   
            <a class="guardar_item" href="#"></a>

        </article>




        {% endfor %}
        
        {% else %}
            NO HAY SOLICITUDES.
        {% endif %}


{% if especialidad.has_other_pages %}
  <ul class="pagination">
    {% if especialidad.has_previous %}
      <li><a href="?page={{ especialidad.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in especialidad.paginator.page_range %}
      {% if especialidad.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if especialidad.has_next %}
      <li><a href="?page={{ especialidad.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}


    </section>
    </body>
        <br>



{% endblock %}