Pedidoapp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from .import views
from django.contrib.auth.views import login_required


from Pedidoapp.views import home, Cant_ingresar, ListAll, ListEspeci, Cant_update, PedidoExtra
from Pedidoapp.views import ExtraView, Cant_upex, Update_stockex, ReportePedidosPDF, ReporteTotalPDF, ReporteTotalFarmacia, ReporteTotalEcono 
from Pedidoapp.views import Reset, Acces_open, Acces_close, VistaAsigna, Asigna, DeletePedido, IngresarExtra, VerTodo, Entregar, Ped_entregados, ListAllEnt, Esp_total, ReportePedidoExtra

admin.autodiscover()

urlpatterns = [

url(r'^home/', login_required(home), name="home"),
url(r'^pedidos-entregados/$', login_required(Ped_entregados), name="ped_entre"),
url(r'^especialidades/$', login_required(Esp_total), name="esp_total"),


url(r'^lista_super/(?P<id_especialidad>\d+)/$', login_required(ListAll), name='lita_todo'),
url(r'^lista_super_entregados/(?P<id_especialidad>\d+)/$', login_required(ListAllEnt), name='lita_todo_entre'),

url(r'^lista_active/(?P<id_especialidad>\d+)/$', login_required(ListEspeci), name='lita_active'),

url(r'^ingresar/(?P<id_pedido>\d+)/(?P<id_especialidad>\d+)/$', Cant_ingresar, name="cant_ingresar"),
url(r'^modificar/(?P<id_pedido>\d+)/(?P<id_especialidad>\d+)/$', Cant_update, name="cant_update"),
url(r'^entregar/(?P<id_especialidad>\d+)/$', Entregar, name="entregar"),

url(r'^pedido-extra/(?P<id_especialidad>\d+)/$', PedidoExtra , name='pedido_extra'),
url(r'^pedidos-extra/$', ExtraView , name='ped_ex'),
url(r'^modificar/(?P<id_pedido_ex>\d+)/$', Cant_upex, name="cant_extra"),
url(r'^ingresa-extra/(?P<id_especialidad>\d+)/(?P<cod_experto>[^/]+)/$', IngresarExtra, name="ingresa_extra"),
url(r'^entregar/(?P<id_pedido_ex>\d+)/(?P<cod_experto>[^/]+)/$', Update_stockex, name="entregado_ex"), 

url(r'^reset-estadis/$', login_required(Reset), name="reset"),
url(r'^acces-open/$', login_required(Acces_open), name="open"),
url(r'^acces-close/$', login_required(Acces_close), name="close"),

url(r'^reporte_pedidos_pdf/(?P<id_especialidad>\d+)/$', login_required(ReportePedidosPDF.as_view()), name="reporte_pedidos_pdf"),
url(r'^reporte_insumo_pdf/$', login_required(ReporteTotalPDF.as_view()), name="reporte_insumo_pdf"),
url(r'^reporte_farmacia_pdf/$', login_required(ReporteTotalFarmacia.as_view()), name="reporte_farma_pdf"),
url(r'^reporte_economato_pdf/$', login_required(ReporteTotalEcono.as_view()), name="reporte_econo_pdf"),
url(r'^reporte_extras_pdf/$', login_required(ReportePedidoExtra.as_view()), name="reporte_pedido_extra_pdf"),

url(r'^asignar-nuevo/(?P<id_especialidad>\d+)/$', login_required(VistaAsigna), name='vista_asigna'),
url(r'^vista-art-extra/(?P<id_especialidad>\d+)/$', login_required(VistaAsigna), name="vista_extra"),
url(r'^btn-asigna/(?P<id_especialidad>\d+)/(?P<cod_experto>[^/]+)/$', Asigna, name="asignar"),
url(r'^delete-pedido/(?P<id_pedido>\d+)/(?P<id_especialidad>\d+)/(?P<cod_experto>[^/]+)/$', DeletePedido, name="confirm_delete_pedido"),
url(r'^ver_todo/(?P<id_especialidad>\d+)/$', login_required(VerTodo), name='ver_todo'),



]   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)      

bodega/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from Pedidoapp import urls
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf import settings


admin.autodiscover()


urlpatterns = [
    # Examples:
    url(r'^solicitar/', include(urls, namespace="usuario")),
  #  url(r'^home_user/$', login_required(Pedidoapp.views.homeuser), name="homeuser"),
    #url(r'^add/$', login_required(add), name=""), 

    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli /',include('grappelli.urls')),
    url(r'^grappelli /',include('grappelli.urls')),
    url(r'^accounts/login/', login, {'template_name':'login.html'}, name="login"),
    url(r'^$', login, {'template_name':'login.html'}, name="login"),
    url(r'^logout/', logout_then_login, name="logout"),


    

]

Pedidoapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Pedido, Especialidad, Articulo, Pedido_Extra


class PedidoEditForm(forms.ModelForm):
    cantidad       = forms.IntegerField(widget=forms.TextInput(attrs={'multiple': True}))

    class Meta:
        model = Pedido


        fields = [

        'cantidad',

        ]  

class PedAdminEditForm(forms.ModelForm):
    cantidad_update       = forms.IntegerField(label='Cantidad:', widget=forms.TextInput(attrs={'type':'number'}))

    class Meta:
        model = Pedido


        fields = [

        'cantidad_update',

        ] 

class EstadisticaForm(forms.ModelForm):
    estadistica    = forms.IntegerField(label='Estadistica Mensual:', widget=forms.TextInput(attrs={'placeholder':'Ingrese numero pacientes'}))  
    
    class Meta:
        model = Especialidad

        fields = [

        'estadistica',

        ]

class ExtraForm(forms.ModelForm):
    cantidad_ex       = forms.IntegerField(label='Cantidad:', widget=forms.TextInput(attrs={'size':'10'}))
    

    class Meta:
        model = Pedido_Extra


        fields = [
        'cantidad_ex',
        
        ]

Pedidoapp/views.py
#!/usr/bin/env python
#-*- coding: utf-8 -*- 

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from Pedidoapp.models import Pedido, Especialidad, Encargado, Articulo, Bodega, Pedido_Extra
from django.shortcuts import render_to_response
from django.template.loader import get_template
from django.template import Context
from datetime import datetime
from Pedidoapp.forms import PedidoEditForm,PedAdminEditForm, EstadisticaForm, ExtraForm
from django.template.context import RequestContext
from django.template import RequestContext
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.shortcuts import get_list_or_404, get_object_or_404
from django.db import models
from django.db.models import Count
from django.core.urlresolvers import reverse
import datetime
from django.utils import timezone
from django.views.generic import CreateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import psycopg2
import sys
import json

from django.contrib.auth.views import login


#modificar filtracion de las especialidades no es necesario mostrar numero de articulos, aun asi, si el numero de entregados
#o el numero de pendientes filtrar por estos camopos: esp = Especialida
def home(request):
    user = request.user
    if user.is_superuser:
      especialidad = Especialidad.objects.filter(estado="pendiente")
      acceso = Especialidad.objects.filter(acceso=0)
      count = Especialidad.objects.filter(estado="pendiente").count()
      count2 = Especialidad.objects.filter(estado="entregado").count()
      count3 = Especialidad.objects.all().count()
      count4 = Especialidad.objects.filter(estado="completado").count() 

      page = request.GET.get('page', 1)

      paginator = Paginator(especialidad, 5)
      try:
            especialidad = paginator.page(page)
      except PageNotAnInteger:
            especialidad = paginator.page(1)
      except EmptyPage:
            especialidad = paginator.page(paginator.num_pages)

      return render(request, "indexadmin.html", {'especialidad':especialidad, 'count':count, 'count2':count2, 'count3':count3, 'acceso':acceso})

    elif user.is_active: 
      especialidad  = Especialidad.objects.filter(encargado__usuario=user.id)
      template2 = "index3.html"
      return render(request, template2, { 'especialidad':especialidad })



def Ped_entregados(request):
    user = request.user
    if user.is_superuser:
      especialidad = Especialidad.objects.filter(estado="entregado").order_by('nombre')
      acceso = Especialidad.objects.filter(acceso=0)
      count = Especialidad.objects.filter(estado="pendiente").count()
      count2 = Especialidad.objects.filter(estado="entregado").count()
      count3 = Especialidad.objects.all().count()
      template = "indexadmin.html"
      page = request.GET.get('page', 1)

      paginator = Paginator(especialidad, 5)
      try:
            especialidad = paginator.page(page)
      except PageNotAnInteger:
            especialidad = paginator.page(1)
      except EmptyPage:
            especialidad = paginator.page(paginator.num_pages)

      return render(request, template, {'especialidad':especialidad, 'count':count, 'count2':count2, 'count3':count3, 'acceso':acceso})


def Esp_total(request):
      user = request.user
      if user.is_superuser:
         especialidad = Especialidad.objects.all().order_by('nombre')
         acceso = Especialidad.objects.filter(acceso=0)
         count = Especialidad.objects.filter(estado="pendiente").count()
         count2 = Especialidad.objects.filter(estado="entregado").count()
         count3 = Especialidad.objects.all().count()
         template = "indexadmin.html"
         page = request.GET.get('page', 1)

         paginator = Paginator(especialidad, 5)
         try:
                  especialidad = paginator.page(page)
         except PageNotAnInteger:
                  especialidad = paginator.page(1)
         except EmptyPage:
                  especialidad = paginator.page(paginator.num_pages)

         return render(request, template, {'especialidad':especialidad, 'count':count, 'count2':count2, 'count3':count3, 'acceso':acceso})


#LISTA ADMIN PENDIENTES
@cache_page(1000)
@login_required
def ListAll(request, id_especialidad):
  especialidad = Especialidad.objects.get(id=id_especialidad)
  if request.method == 'GET':
        pedido = Pedido.objects.filter(especialidad=especialidad).filter(estado='pendiente').order_by('-estado').order_by('articulo')
        template  = 'admindata.html'
        return render(request, template, {'pedido':pedido, 'especialidad':especialidad})

#LISTA ADMIN ENTREGADOS
@cache_page(1000)
@login_required
def ListAllEnt(request, id_especialidad):
  especialidad = Especialidad.objects.get(id=id_especialidad)
  if request.method == 'GET':
        pedido = Pedido.objects.filter(especialidad=especialidad).filter(estado='entregado').order_by('articulo')
        template  = 'admindata2.html'
        return render(request, template, {'pedido':pedido, 'especialidad':especialidad})



#LISTA ACTIVO
@cache_page(1000)
@login_required
def ListEspeci(request, id_especialidad):
      especialidad = Especialidad.objects.get(id=id_especialidad)
      pedido2 = Pedido.objects.filter(especialidad=especialidad).filter(estado='pendiente').order_by('-articulo')
      pedido3 = Pedido.objects.filter(especialidad=especialidad).filter(estado='entregado').order_by('-articulo')
      pedido = Pedido.objects.filter(especialidad=especialidad)
      if request.method == 'GET':
            form = EstadisticaForm(instance=especialidad)
      else:
            form = EstadisticaForm(request.POST, instance=especialidad)
            if form.is_valid():
                  form.save()
            return HttpResponseRedirect('/solicitar/lista_active/%s/' % id_especialidad)
      return render(request, 'index2.html', { 'form':form, 'pedido':pedido, 'pedido2':pedido2, 'pedido3':pedido3, 'especialidad':especialidad})
 


#BTN INGRESAR ACTIVO
@login_required
@cache_page(1000)
def Cant_ingresar(request, id_pedido, id_especialidad):
    especialidad = Especialidad.objects.get(id=id_especialidad)
    pedido = Pedido.objects.get(id=id_pedido)
    
    if request.method == 'GET':
      form = PedidoEditForm(instance=pedido)
    else:
      form = PedidoEditForm(request.POST, instance=pedido)
      if form.is_valid():
          form.save()
          pedido2 = Pedido.objects.filter(id=id_pedido).update(estado="pendiente", fecha_pedido=timezone.now())
          Especialidad.objects.filter(id=id_especialidad).update(estado="pendiente")
      return HttpResponseRedirect('/solicitar/lista_active/%s/' % id_especialidad)
    return render(request, 'form.html', {'form':form, 'pedido':pedido, 'especialidad':especialidad, 'pedido':pedido}) 


#BTN MODIFICAR ADMIN
@login_required
@cache_page(1000)
def Cant_update(request, id_pedido, id_especialidad):
    especialidad = Especialidad.objects.get(id=id_especialidad)
    pedido = Pedido.objects.get(id=id_pedido)
    if request.method == 'GET':
      form = PedAdminEditForm(instance=pedido)
    else:
      form = PedAdminEditForm(request.POST, instance=pedido)
      if form.is_valid():
          form.save()
          pedido.estado_update = 'modificado'
          pedido.save()
      return HttpResponseRedirect('/solicitar/lista_super/%s/' % id_especialidad)
    return render(request, 'form3.html', {'form':form, 'pedido':pedido, 'especialidad':especialidad})



from django.views.generic import ListView, DetailView
   

class PedidoDetailView(DetailView):
    model = Pedido
    def get_template_names(self):
        return render('index.html')


#BTN ENTREGADO
@login_required
def Entregar(request, id_especialidad):
    especialidad = Especialidad.objects.get(id=id_especialidad)
    pedido3 = Pedido.objects.filter(especialidad=especialidad).filter(estado='pendiente').update(fecha_entrega=timezone.now())
    for ped in Pedido.objects.filter(especialidad=especialidad).filter(estado='pendiente'):
      ped.estado = "entregado"
      ped.save()
      if ped.estado_update == "modificado":
            ped.articulo.stock -= ped.cantidad_update
      else: 
            ped.articulo.stock -= ped.cantidad
            ped.save()
    especialidad.estado = 'entregado'
    especialidad.save()
    return HttpResponseRedirect('/solicitar/reporte_pedidos_pdf/%s/' % id_especialidad)



#Ingresar cantidad de articulo extra
@login_required
def PedidoExtra(request, id_especialidad):
    especialidad = Especialidad.objects.get(id=id_especialidad)
    if request.method == 'GET':
      form = ExtraForm()
    else:
      form = ExtraForm(request.POST)
      if form.is_valid():
        esp = form.save(commit=False)
        esp.especialidad_ex = especialidad
        esp.save()
        form.save()
      return HttpResponseRedirect('/solicitar/home/')
    return render(request, 'form2.html', {'form':form, 'especialidad':especialidad})

#vista para admin y activo de extras
@login_required
def ExtraView(request):
      user = request.user
      if user.is_superuser:
        extra = Pedido_Extra.objects.filter(estado_ex='pendiente')
        return render(request, 'extra.html', {'extra':extra, 'user':user})
      else:
        extra = Pedido_Extra.objects.filter(especialidad_ex__encargado__usuario=user.id)
        return render(request, 'extra.html', {'extra':extra, 'user':user})

#admin modifica cantidad extra
@login_required
def Cant_upex(request, id_pedido_ex):
    extra = Pedido_Extra.objects.get(id=id_pedido_ex)
    if request.method == 'GET':
      form = ExtraForm(instance=extra)
    else:
      form = ExtraForm(request.POST, instance=extra)
      if form.is_valid():
          form.save()
          extra.save()
      return HttpResponseRedirect('/solicitar/pedidos-extra/')

Pedidoapp/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">


   

    {% block extrahead %}
    {% endblock %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all"/>


    <title>{% block title %}S.G.I{% endblock %}</title>
    <link rel="shortcut icon" href="http://siremo.conapesca.gob.mx/prope/images/registro.png" />
</head>

<div class="container">
    {% block navbar %}
        <div class="bs-docs-section clearfix">
            <div class="row">
                <div class="col-lg-12">
                    <div class="bs-component">
                        <nav class="navbar navbar-default navbar-fixed-top" > 
                            <div class="container-fluid">
                                <div class="navbar-header">
                                    <a class="navbar-brand" href="{% url "usuario:home"  %}">Home</a>
                                </div>
                                <div class="navbar-header">
                                    <a class="navbar-brand" href=""></a>
                                </div>
                                <div class="navbar-header">
                                    <a class="navbar-brand" href="{% url "usuario:ped_ex"  %}">Extras</a>
                                </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="dropdown">
                                        </ul>
                                    </li>                                       
                                </ul>
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown"><a href="{% url "usuario:home"  %}">{% if not request.user.is_authenticated %}
        {% else %}
            Hola {{request.user}}!
        {% endif %}</a>                                   
                                </li> 
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown"><a href="{% url 'admin:index' %}" target=_blank >Admin</a>                                   
                                    </li>                                  
                                    <li class="dropdown">
                                        <li class="dropdown"><a href="{% url 'logout' %}">Cerrar</a>

                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
<br>
<br>
<br>
<br>
    <nav>
        <ul>
            <li id="flechita_nav"><a href="/"></a></li>
            
            <li id="publicar_nav"><a href="">S.G.I</a></li>
        </ul>
    </nav>

 {% endblock %}


    {% block content %}
    <h4>    Bloque de contenido     </h4>
    {% endblock %}


    {% block footer %}
        </section>

    <footer>
        <p><strong>Powered by Demaro!</strong></p>
        <p>S.G.I for CAE-HRR. 2017 ®</p>
    </footer>

    {% endblock%}
</div>

    {% block extrajs %}
    {% endblock %}


</body>

</html>

Pedidoapp/templates/base/header.html
<header>Hola </header>